name = "FilonExperiments"
authors = ["Spencer Lee"]

[deps]
DrWatson = "634d3b9d-ee7a-5ddf-bec9-22491ea816e1"
FilonResearch = "3a284e70-3988-4fde-94af-e81b1d70ca0a"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
OrdinaryDiffEqVerner = "79d7bb75-1356-48c1-b8c0-6832512096c2"
QuantumGateDesign = "f716b271-9d99-4329-8adc-fa1e42d5b881"
SlurmClusterManager = "c82cd089-7bf7-41d7-976b-6b5d413cbe0a"

[sources]
FilonResearch = {path = ".."}
QuantumGateDesign = {url = "https://github.com/leespen1/QuantumGateDesign.jl.git"}

[compat]
DrWatson = "2.19.1"
julia = "1.12.5"
